language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "6"
  - "stable"

install:
  - npm install
  - typings install

before_script:
  - npm run clean
  - npm run build

after_script:
  - npm install coveralls
  - cat ./coverage-final/lcov.info | coveralls